-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 13:19:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chrono_dev_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chrono_dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chrono_dev_db` DEFAULT CHARACTER SET utf8 ;
USE `chrono_dev_db` ;

-- -----------------------------------------------------
-- Table `chrono_dev_db`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chrono_dev_db`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `initial_mileage` INT NOT NULL,
  `created_at` VARCHAR(90) NOT NULL,
  `updated_at` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chrono_dev_db`.`CategoryMain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chrono_dev_db`.`CategoryMain` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(90) NOT NULL,
  `updated_at` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chrono_dev_db`.`CategorySub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chrono_dev_db`.`CategorySub` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(90) NOT NULL,
  `updated_at` VARCHAR(90) NOT NULL,
  `CategoryMain_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_CategorySub_CategoryMain`
    FOREIGN KEY (`CategoryMain_id`)
    REFERENCES `chrono_dev_db`.`CategoryMain` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CategorySub_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `chrono_dev_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chrono_dev_db`.`Expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chrono_dev_db`.`Expense` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `created_at` VARCHAR(90) NOT NULL,
  `updated_at` VARCHAR(90) NOT NULL,
  `mileage` INT NOT NULL,
  `CategorySub_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Expense_CategorySub1`
    FOREIGN KEY (`CategorySub_id`)
    REFERENCES `chrono_dev_db`.`CategorySub` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chrono_dev_db`.`Alert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chrono_dev_db`.`Alert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mileage_limit` INT NOT NULL,
  `mileage_act` INT NOT NULL,
  `high` INT NOT NULL,
  `middle` INT NULL,
  `low` INT NULL,
  `created_at` VARCHAR(90) NOT NULL,
  `updated_at` VARCHAR(90) NOT NULL,
  `CategorySub_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Expense_CategorySub10`
    FOREIGN KEY (`CategorySub_id`)
    REFERENCES `chrono_dev_db`.`CategorySub` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
